### ISSUE TITLE
POlice menu ?

### ISSUE THREAD

**Issue by cedricalpatch** [Sighmir/vrp_dmvschool#1]
Hello 

This impossible to askid ??
I have check in police module, police cfg, add and modif pemission etc etc ... Impossible to isk id??

Thanks

**Comment by Sighmir** [comment]
This just adds an Check License button that works with the same permission as ask id thus you don't have to change anything for it to work, it will ask the closest player to show his license if he does it checks the license if its REQUIRED or OK if the person refuses it tells the player who requested the request got refused.
You don't have to modify anything anywhere for this to work. I believe this is working as intended.
Ask ID is part of vRP not DMV_School.

**Comment by cedricalpatch** [comment]
I know what you say but when we ask id we havent the driver licence ?
Just address , nam , etc...
So I have check you script and all is here for but not work?
I understand very well the vrp and permission system this one year I use...
the police.askid is been in user and police permission but we dont see on the police menu for ask?

**Comment by Sighmir** [comment]
The vrp_dmvschool adds a button Check License, the license doesnt show under ID.
