### ISSUE TITLE
No such command vrp_dmvschool.

### ISSUE THREAD

**Issue by hardlevel** [Sighmir/vrp_dmvschool#4]
Hi...

I inserted the vrp_dmvschool in my resources folder, after that add in my cfg to start, inserted at the end of the mods to start

But when I start the server, I got this error: No such command vrp_dmvschool.

What I have to do?

**Comment by Sighmir** [comment]
You are not adding the command "start vrp_dmvschool" to your server.cfg properly.

**Comment by hardlevel** [comment]
vc é brasileiro?

yes, I did, is everything OK in server.cfg, I reinstalled everything and the error is gone, but, I can't find where the school is... can you tell me please?

**Comment by Sighmir** [comment]
Issues on GitHub will stay in english to help everyone. 
The error  "No such command vrp_dmvschool." is a message from FiveM to indicate a wrong command in your server.cfg so I believe you might have forgotten the "start" as its seeing "vrp_dmvschool" as a command.
